on:
  push:
    branches:
      - feature-deploy-page

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Set Git Identity
        run: |
          git config user.email "jeremy.ondrey@threedy.io"
          git config user.name "jondreyThreedy"

      - name: Build and Deploy
        run: npm run deploy
